### ISSUE TITLE
Please add EDMC StartUp Event to your code

### ISSUE THREAD

**Issue by robbyxp1** [Thurion/DistanceCalc#11]
Makes it more robust to various combinations of EDMC starting conditions

def journal_entry(cmdr, is_beta, system, station, entry, state):
    if entry["event"] == "FSDJump" or entry["event"] == "Location" or entry["event"] == "StartUp":

Thanks

**Comment by Thurion** [comment]
Added in commit f541a0d1b8d6604b576f25f43d5ea70ed40981f7
