### ISSUE TITLE
Sagittarius A* not working

### ISSUE THREAD

**Issue by Crunkstar** [Thurion/DistanceCalc#9]
Sagittarius A* isn't working, when getting the data from EDSM it doesn't fill in the Z value and when typing it in manually the width of the textbox for the Z value isn't long enough.

**Comment by Thurion** [comment]
You could copy & paste the value in there if it doesn't fit.
When I press the EDSM button for Sag A* it fills in all information including the Z value.

What system language and locale do you use? Maybe there is something off with the validation for the input fields.
Can you also please check if there is something in the `EDMarketConnector.log`? It should be located in `%temp%`.

**Comment by Crunkstar** [comment]
The log file just contains the load up stuff.

When I try to paste the whole Z coordinate "25899.96875" it won't work, it'll only work with "25899.9687" so 1 character less and that won't give me the correct distance to Sagittarius A*.

My whole system is set to german, also the keymap and almost every program I use (including ED Market Connector) is set to english.

**Comment by Thurion** [comment]
Please download the latest release: https://github.com/Thurion/DistanceCalc/releases/tag/rel-121

I also did some testing and if you write a comma (comma or dot depending on your Windows settings) you can add decimal places even if the textbox is full. It scrolls in that case.
